### ISSUE TITLE
[DUPE] effortless building allows you to dupe wood frames

### ISSUE THREAD

**Issue by rogerwim** [Nomi-CEu/Nomi-Labs#14]
# how to reproduce:
place down wood frames in a like 5x5x1 block
select a effortless building mode
click on frames with sprayer
# what i expect to happen:
frames get sprayed
# what happens:
frames do not get sprayed, and each frame causes a frame to drop as a item

**Comment by rogerwim** [comment]
NOTE: this ONLY works with WOODEN frames

**Comment by IntegerLimit** [comment]
Fixed in https://github.com/Nomi-CEu/Nomi-Labs/commit/57e1b08a0f3ea1e2aa600dfa118c56914005c14a.
