### ISSUE TITLE
Stabilized Micro Miners have the Pristine Matter tooltip

### ISSUE THREAD

**Issue by NotMyWing** [Nomi-CEu/Nomi-Labs#21]
The "looks familiar" flavor text was intended for Pristine Matter as a homage to them being not-DML, not Micro Miners.

https://github.com/Nomi-CEu/Nomi-Labs/blob/860833a87b0ed4cf05afa91dfdd6bf76d8ef569d/src/main/resources/assets/nomilabs/lang/en_us.lang#L565-L569

**Comment by IntegerLimit** [comment]
Ah, I see. Will correct, thank you.
