### ISSUE TITLE
Error spam when looking at GTCEu machines. 

### ISSUE THREAD

**Issue by Sar4h-3** [Nomi-CEu/Nomi-Labs#26]
Pack: 
- Nomifactory 1.7a

Related mods: 
- GTCEu: 2.8.10-beta
- Nomilabs: 0.8.20

Environment: 
- Singleplayer

When looking at any GT machine with a tank, the console will be spammed by this error: 
`[Netty Local Client IO #0/ERROR] [nomilabs]: Received Fluid Info Packet ElementTankGauge with Unknown Fluid !`

Steps to reproduce: 
- place down any GT machine with a internal tank (like an assembler)
- look at the machine

**Comment by IntegerLimit** [comment]
Fixed in latest (actions) build.
