### ISSUE TITLE
[Cleanroom] Narrator class not found

### ISSUE THREAD

**Issue by alexey-va** [Nomi-CEu/Nomi-Labs#31]
https://mclo.gs/30I5RVX

**Comment by alexey-va** [comment]
recompiled without narrator mixin and it solved the issue for me

**Comment by IntegerLimit** [comment]
Which version of cleanroom? Did you add Fugue?

**Comment by alexey-va** [comment]
I am using Cleanroom 0.2.3-alpha with Fugue 0.16.4 and Scalar. Restricting this mixin to dev would be great.
