### ISSUE TITLE
Crash when selecting area with Effortless Building

### ISSUE THREAD

**Issue by ChromaPIE** [Nomi-CEu/Nomi-Labs#33]
Occasionally happens, not everytime, seems like an edge case.

Related part from the log: https://mclo.gs/dAEsdvr

**Comment by IntegerLimit** [comment]
That really shouldn't happen, there is a containsKey check before. I'll replace it with a null check, see if that fixes it.

**Comment by IntegerLimit** [comment]
Can you send the full client and server `debug.log`? I want to find out why it is null.

**Comment by IntegerLimit** [comment]
I will close this issue based on the above implementation, but please still send the logs, so the issue can be better diagnosed.

**Comment by ChromaPIE** [comment]
it's actually super hard to reproduce. I use EB a lot but i only happened exactly two times. anyway i'll use the dev build and send the debug log if it happens again.

**Comment by IntegerLimit** [comment]
Thanks!
